#Database Configuration
spring.datasource.url= jdbc:mysql://localhost:3306/schoolmanagementsystem
spring.datasource.username= root
spring.datasource.password= 1234
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:schoolmanagementsystem
#spring.jpa.show-sql=true

#spring.profiles.active=dev
# Disable default whitelabel error page
#server.error.whitelabel.enabled=false
# Enable 404 handling
#spring.mvc.throw-exception-if-no-handler-found=true